config/routes.rb
Rails.application.routes.draw do
  resources :events, except: :index
  get "/common_events/new" => "events#common_new"
  post "/common_events" => "events#common_create"
  get "/common_events/:id/edit" => "events#common_edit"
  patch "/common_events/:id" => "events#common_update"

  devise_for :users, only: [:sessions, :registrations]
  resources :users, only: [:show, :index]
  root 'users#top'
end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :user
  belongs_to :group

  validate :add_error_message

  def add_error_message
    if title.empty?
      errors[:base] << "タイトルを入力してください"
    end
  end

end

app/models/group.rb
class Group < ActiveRecord::Base

  #association
  has_many :users
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base

  #accessor
  attr_accessor :group_key

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :recoverable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         authentication_keys: [:email, :group_key]

  #association
  belongs_to :group
  has_many :events

  #validation
  before_validation :group_key_to_id, if: :has_group_key?

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    group_key = conditions.delete(:group_key)
    group_id = Group.where(key: group_key).first
    email = conditions.delete(:email)

    # devise認証を、複数項目に対応させる
    if group_id && email
      where(conditions).where(["group_id = :group_id AND email = :email",
        { group_id: group_id, email: email }]).first
    elsif conditions.has_key?(:confirmation_token)
      where(conditions).first
    else
      false
    end
  end

  private
  def has_group_key?
    group_key.present?
  end

  def group_key_to_id
    group = Group.where(key: group_key).first_or_create
    self.group_id = group.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys:[:group_key])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :group_key])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :common_edit, :common_update]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  def common_new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  def common_edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to "/users/#{current_user.id}" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def common_create
    @event = Event.new(common_event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to "/users" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def common_update
    respond_to do |format|
      if @event.update(common_event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    redirect_to root_path
    # respond_to do |format|
    #   format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start, :end, :allDay).merge(color: "#5bb9f8", user_id: current_user.id, group_id: current_user.group_id, common: false)
    end

    def common_event_params
      params.require(:event).permit(:title, :start, :end, :allDay).merge(color: "#7edf77", user_id: current_user.id, group_id: current_user.group_id, common: true)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

    @events = Event.where(["user_id = ? and common = ?", @user.id, false]).or(Event.where(["group_id = ? and common = ?", @user.group_id, true])).map{|e|
    {
    :id => e.id,
    :title => e.title,
    :start => e.start,
    :end => e.end,
    :color => e.color,
    :allDay => e.allDay,
    :url => event_path(e.id)
    }
    }

    respond_to do |format|
    format.html
    format.xml { render :xml => @events }
    format.json { render :json => @events }
    end
  end

  def top
    redirect_to "/users/#{current_user.id}"
  end

  def index
    @users = User.where(group_id: current_user.group_id)
    @events = Event.where(["group_id = ? and common = ?", current_user.group_id, true]).map{|e|
    {
    :id => e.id,
    :title => e.title,
    :start => e.start,
    :end => e.end,
    :color => e.color,
    :allDay => e.allDay,
    :url => event_path(e.id)
    }
    }

    respond_to do |format|
    format.html
    format.xml { render :xml => @events }
    format.json { render :json => @events }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :タイトル %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :開始日時 %><br>
    <%= f.datetime_select :start, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :終了日時 %><br>
    <%= f.datetime_select :end, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :終日 %><br>
    <%= f.check_box :allDay %>
  </div>
  <div class="actions form-group">
    <%= f.submit "予定を保存する", class:"btn btn-default" %>
  </div>
<% end %>

app/views/events/common_edit.html.erb
<h1 class="event-form-title">グループの予定を編集する</h1>

<%= form_tag("/common_events/#{@event.id}", method: :patch) do %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= label :event, :タイトル %><br>
    <%= text_field :event, :title, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label :event, :開始日時 %><br>
    <%= datetime_select :event, :start, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label :event, :終了日時 %><br>
    <%= datetime_select :event, :end, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label :event, :終日 %><br>
    <%= check_box :event, :allDay %>
  </div>
  <div class="actions form-group">
    <%= submit_tag "予定を保存する", class:"btn btn-default" %>
  </div>
<% end %>

<%= link_to '詳細へ戻る', @event %>

app/views/events/common_new.html.erb
<h1 class="event-form-title">グループの予定を追加する</h1>

<%= form_tag("/common_events", method: :post) do %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= label :event, :タイトル %><br>
    <%= text_field :event, :title, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label :event, :開始日時 %><br>
    <%= datetime_select :event, :start, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label :event, :終了日時 %><br>
    <%= datetime_select :event, :end, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= label :event, :終日 %><br>
    <%= check_box :event, :allDay %>
  </div>
  <div class="actions form-group">
    <%= submit_tag "予定を保存する", class:"btn btn-default" %>
  </div>
<% end %>

<%= link_to 'グループページに戻る', users_path, method: :get %>

app/views/events/edit.html.erb
<h1 class="event-form-title">予定を編集する</h1>

<%= render 'form' %>

<%= link_to '詳細へ戻る', @event %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start</th>
      <th>End</th>
      <th>Allday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start %></td>
        <td><%= event.end %></td>
        <td><%= event.allDay %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1 class="event-form-title">予定を追加する</h1>

<%= render 'form' %>

<%= link_to 'マイページに戻る', user_path(current_user.id), method: :get %>

app/views/events/show.html.erb
<h1 style="font-size: 18px;">予定の詳細</h1>

<p>
  <strong>タイトル:</strong>
  <%= @event.title %>
</p>

<% if @event.allDay == false %>
  <p>
    <strong>開始時間:</strong>
    <%= @event.start %>
  </p>

  <p>
    <strong>終了時間:</strong>
    <%= @event.end %>
  </p>

<% else %>

  <p>
    <strong>終日:</strong>
    ○
  </p>

<% end %>

<% if @event.common == true %>
  <%= link_to '編集する', "/common_events/#{@event.id}/edit" %> |
  <%= link_to '削除する', "/events/#{@event.id}", method: :delete, data: { confirm: '本当に削除しますか?' } %>
<% elsif user_signed_in? && @event.user_id == current_user.id %>
  <%= link_to '編集する', edit_event_path(@event) %> |
  <%= link_to '削除する', "/events/#{@event.id}", method: :delete, data: { confirm: '本当に削除しますか?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "CalendarApp", user_path(current_user.id), method: :get, class: "navbar-brand" %>
      </div>

      <div class="collapse navbar-collapse target">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "マイページ", user_path(current_user.id), method: :get %></li>
          <li><%= link_to "グループページ", users_path, method: :get %></li>
            <li class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown">
                ユーザー設定 <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "アカウント編集", edit_user_registration_path, method: :get %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              </ul>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="navbar-header">
        <button class="navbar-toggle" data-toggle="collapse" data-target=".target">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand">CalendarApp</span>
      </div>
      <div class="collapse navbar-collapse target">
        <ul class="nav navbar-nav navbar-right">
          <% if controller_name != 'sessions' %>
            <li><%= link_to "ログイン", new_session_path(resource_name) %></li>
          <% else %>
            <li><%= link_to "アカウント登録", new_registration_path(resource_name) %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/users/index.html.erb
<h1 style="margin-bottom: 20px;"><span><%= current_user.group.key %></span> のメンバー</h1>
<ul class="user-list">
  <% @users.each do |user| %>
    <li><span>・<%= user.name %>さん</span><%= link_to "カレンダーを見る", user_path(user.id), method: :get %></li>
  <% end %>
</ul>

<h1 style="margin-top: 50px;"><span><%= current_user.group.key %></span> の共通カレンダー</h1>

<p class="add-event"><%= link_to "グループの予定を追加する", common_events_new_path, method: :get, class:"btn btn-default" %></p>

<div id="calendar"></div>

<script>

  $(document).ready(function() {
    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      events: '/users.json',
      ignoreTimezone: false,
      eventLimit: true,
      timeFormat: 'H(:mm)',
      buttonText: {
          today:    '今日',
          month:    '月',
          week:     '週',
          day:      '日'
      },
      monthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
      monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
      dayNames: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
      dayNamesShort: ['日', '月', '火', '水', '木', '金', '土']
    });
  });

</script>

app/views/users/show.html.erb
<h1><span><%= @user.name %></span> さんのカレンダー</h1>

<% if user_signed_in? && @user.id == current_user.id %>
  <p><%= link_to "予定を追加する", new_event_path, method: :get, class:"btn btn-default btn-add-event" %></p>
<% end %>

<div id="calendar"></div>

<script>

  $(document).ready(function() {
    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay'
      },
      events: "/users/<%= @user.id %>.json",
      ignoreTimezone: false,
      eventLimit: true,
      timeFormat: 'H(:mm)',
      buttonText: {
          today:    '今日',
          month:    '月',
          week:     '週',
          day:      '日'
      },
      monthNames: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
      monthNamesShort: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
      dayNames: ['日曜日', '月曜日', '火曜日', '水曜日', '木曜日', '金曜日', '土曜日'],
      dayNamesShort: ['日', '月', '火', '水', '木', '金', '土']
    });
  });

</script>